<?php
namespace Eceon\MVC\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-20 at 14:36:55.
 */
class FrontTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Front
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Front;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Eceon\MVC\Controller\Front::run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eceon\MVC\Controller\Front::setDispatcher
     * @todo   Implement testSetDispatcher().
     */
    public function testSetDispatcher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eceon\MVC\Controller\Front::getDispatcher
     * @todo   Implement testGetDispatcher().
     */
    public function testGetDispatcher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eceon\MVC\Controller\Front::setPluginManager
     * @todo   Implement testSetPluginManager().
     */
    public function testSetPluginManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eceon\MVC\Controller\Front::getPluginManager
     * @todo   Implement testGetPluginManager().
     */
    public function testGetPluginManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eceon\MVC\Controller\Front::setRouter
     * @todo   Implement testSetRouter().
     */
    public function testSetRouter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eceon\MVC\Controller\Front::getRouter
     * @todo   Implement testGetRouter().
     */
    public function testGetRouter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
