<?php
namespace Eceon\MVC\Model\DataMapper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-20 at 14:46:34.
 */
class SqlDataMapperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SqlDataMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SqlDataMapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Eceon\MVC\Model\DataMapper\SqlDataMapper::setConnection
     * @todo   Implement testSetConnection().
     */
    public function testSetConnection()
    {
        
    }
}
