<?php
    
    
    namespace Eceon\MVC\Model\Service;

    use Eceon\MVC\Model\DataMapper\InterfaceDataMapper;
    
    /**
     * Generated by PHPUnit_SkeletonGenerator on 2015-08-20 at 18:57:35.
     */
    class AbstractServiceTest extends \PHPUnit_Framework_TestCase
    {
        /**
         * @var AbstractService
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
            $this->object = $this->getMockForAbstractClass( AbstractService::class );
        }



        public function testAddAndGetDataMapper()
        {
            $new_dataMapper = $this->getMockBuilder( InterfaceDataMapper::class )
                                    ->getMock();

            $this->object->addDataMapper( 'test_datamapper', $new_dataMapper );

            $this->assertSame( $new_dataMapper, $this->object->getDataMapper( 'test_datamapper' ) );

            $this->assertInstanceOf( InterfaceDataMapper::class, $this->object->getDataMapper('test_datamapper') );
        }


        public function testGetUnknownDataMapper()
        {
            $datamapper_name = 'unknow_datamapper_name';

            $this->assertNull( $this->object->getDataMapper( $datamapper_name ) );
        }


    }
